apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds
      options:
        usepodidentity: "false"
        keyvaultname: "kv-flex-e2e"
        keyvaultobjectnames: secret1
        keyvaultobjecttypes: secret
        # keyvaultobjectversions: ""
        resourcegroup: "keyvault-flexvolume-e2e"
        subscriptionid: "940f88ce-a64b-4e73-a258-9931349b9789"
        tenantid: "72f988bf-86f1-41af-91ab-2d7cd011db47"
